### ISSUE TITLE
New architecture design

### ISSUE THREAD

**Issue by PraveenMNaik** [jinfagang/nb#9]
How to use this package to write new architecture...
IS this package useful for representing in .yaml file for yolov5.... or .cfg files for trainin in yolov4, yolov3 etc

**Comment by jinfagang** [comment]
Yes, you can using it to build yolov5 arch.

**Comment by PraveenMNaik** [comment]
how o use the package... pls upload demo please

**Comment by PraveenMNaik** [comment]
what is the output of the package use... ayaml file?

**Comment by PraveenMNaik** [comment]
what is the output of the package use... a .yaml file?

**Comment by jinfagang** [comment]
README.md
